version: '3'
services:
  zookeeper:
    hostname: zookeeper
    ports:
      - 2181:2181
    image: wurstmeister/zookeeper
    container_name: zookeeper


  kafka:
    hostname: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CREATE_TOPICS: >
        fb-event.card-created:1:1,
        fb-event.card-created,
        fb-event.board-created:1:1,
        fb-event.board-created,
        fb-event.card-status-changed:1:1,
        fb-event.card-status-changed,
        fb-event.team-created:1:1,
        fb-event.team-created,
        fb-event.member-added-to-team:1:1,
        fb-event.member-added-to-team,
        fb-connect.teams.teams,
        fb-view.card-summary:1:1,
#        fb-view.team-ranking:1:1,
#        fb-view.player-goals:1:1,
#        fb-view.player-cards:1:1,
#        fb-view.top-players:1:1,
#        fb-connect.public.players:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 999
    image: wurstmeister/kafka:1.1.0
    container_name: kafka
    links:
      - zookeeper
    expose:
      - "9092"

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

  postgres:
    image: debezium/example-postgres:latest
    container_name: postgres
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"

#  connect:
#    image: debezium/connect:latest
#    container_name: connect
#    ports:
#     - 8083:8083
#    links:
#     - kafka
#     - postgres
#    environment:
#      BOOTSTRAP_SERVERS: localhost:9092
#      GROUP_ID: 1
#      CONFIG_STORAGE_TOPIC: fb.connect.configs
#      OFFSET_STORAGE_TOPIC: fb.connect.offsets
